# Generated by Django 4.2.4 on 2023-08-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_position_alter_customuser_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.schedule'),
        ),
    ]
