# Generated by Django 4.2.4 on 2023-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('side', 'Side'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='main', max_length=20),
        ),
    ]
